# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
                ('published_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
